### ISSUE TITLE
program continuously prints invalid URL error

### ISSUE THREAD

**Issue by yorunoken** [M1ndo/RichSpot#2]
```bash
@yoru in ~ 
💜 richspot
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
^CTraceback (most recent call last):
  File "/home/yoru/.local/bin/richspot", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/yoru/.local/share/pipx/venvs/richspot/lib/python3.12/site-packages/richspot.py", line 146, in run
    getmusic()
  File "/home/yoru/.local/share/pipx/venvs/richspot/lib/python3.12/site-packages/richspot.py", line 108, in getmusic
    data = sock.recv(4096)
           ^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by yorunoken** [comment]
found the cause. Ncspot install doesn't have the `cover` feature.
I think you should have a fallback to rpc without the cover link.

**Comment by M1ndo** [comment]
@yorunoken Thanks for the issue, i'll take a look at it and get back to you.

**Comment by M1ndo** [comment]
> found the cause. Ncspot install doesn't have the `cover` feature.

I don't think the cause is if ncspot cover feature is not built-in by default. ncspot provide metadata of a track by default which contains the track image.

However i'm still uncertain, i'll build a version of ncspot without the cover feature and check if this is the case.
